env: "gymma"

env_args:
  key: null
  time_limit: 500
  state_repre_flag: "onehot"  # new
  pretrained_wrapper: null
  lare_device: "cpu"  # new

test_greedy: True
test_nepisode: 100
test_interval: 50000
log_interval: 50000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 300050000